# Generated by Django 4.2.10 on 2024-02-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kecamatan_kelurahan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAMA', models.CharField(max_length=100)),
                ('PENDATA', models.CharField(max_length=100)),
                ('NIK', models.CharField(max_length=20)),
                ('TELP', models.CharField(max_length=20)),
                ('TPS', models.CharField(max_length=20)),
                ('KEL', models.CharField(max_length=100)),
                ('KEC', models.CharField(max_length=100)),
                ('KAB', models.CharField(max_length=100)),
            ],
        ),
    ]
