# Generated by Django 4.2.10 on 2024-02-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_entrydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('pendata', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=20)),
                ('telp', models.CharField(max_length=20)),
                ('tps', models.CharField(max_length=20)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kelurahan', models.CharField(max_length=100)),
            ],
        ),
    ]
